---
title: "Solution to Exercise 1 - Pipeline - Formative"
author: "LSE Candidate Number: 39033"
date: "Autumn Term 2024"
output: html_document
---


---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
#### Solution to Exercise 1 - Pipeline - Formative 

## Step 1

# Loaded tidyverse 
library(tidyverse)

# Loaded the cars dataset
data(cars)   

# Asked for a summary of the cars dataset
summary(cars) 

# Created a function to calculate time. Added a new column for time to the dataset. Returned the new dataset
calculate_time <- function(cars) {
  
  data <- cars %>%
    mutate(time = round(dist / speed, 1))
  

  return(data)
}

# Applied the function to the cars dataset 
cars_with_time <- calculate_time(cars)

# Viewed the cars data with time added
print(cars_with_time)

# Created a table of the altered cars dataset using tibble 
cars_tibble <- as_tibble(cars_with_time)

# Viewed the new cars tibble
print(cars_tibble) 

```


```{r cars}
## Step 3 

# Sorted time from lowest to highest
sorted_cars_new <- cars_tibble %>%
  arrange(time)

# Viewed the result with new times from lowest to highest
print(sorted_cars)

# Added a column with the type of medal awarded based on times
cars_tibble_tiers <- c %>%
cars_tibble_tiers <- sorted_cars_new %>%
  mutate(
    time_tier = case_when(
      time >= 0 & time < 2 ~ "Gold",
      time >= 2 & time < 4 ~ "Silver",
      time >= 4 & time <= 6 ~ "Bronze"
    )
  )

print(cars_tibble_tiers)

```
